### PR TITLE
WebRTC leak

### PR DESCRIPTION
**Pull request by dsmontoya**
I finally finished this. Now it is possible to get both local and public address, ipv6 and, additionally, a fingerprint which I'm not sure if works for generating entropy.

``` javascript
//Yep! async
client.getWebRTCFingerprint(function(obj){
  console.log(obj.localAddress);
  console.log(obj.publicAddress);
  console.log(obj.fingerprint); // sha-256 33:5C:16:97:31:A9 [...]
});
```

If you have more information about what kind of data from webRTC can be used for generating entropy, please tell me.

@jackspirou: I think we should work on v1, adding callbacks or promises support to the fingerprint generators so that we can use this data-point.

### CODE REVIEW

**Comment by dsmontoya** [comment]
I forgot to mention that modified build.sh. I think that the compiled file should be generated in dist.

**Comment by dsmontoya** [comment]
One last thing. Do you like the name of the method? It's too late so I can't think in a better name.

**Comment by jackspirou** [comment]
@dsmontoya per our other discussion, lets close this and use your current fork of v1.0.0-rc.1.

**Comment by dsmontoya** [comment]
Agreed

**Pull request closed without merging**
