### PR TITLE
Add graceful fails for canvas methods 

### PR DESCRIPTION
**Pull request by ammurphy**
make changes to client.js so that canvas methods fail gracefully for older versions of IE (and perhaps other browsers as well)

### CODE REVIEW

**Comment by jackspirou** [comment]
@ammurphy thanks for the pull request, the changes themselves look good after running a diff: 
screen shot 2015-06-10 at 8 43 36 pm

Was there any reason that you couldn't edit the file in `clientjs/src/client.js` and then run the script at  `clientjs/build.sh` to compile the new version?  

If you having trouble with anything let me know, I would like to make the process easier to contribute if this seems to be a hangup. 

Thanks for you help.

**Comment by ammurphy** [comment]
Hi Jack,
Thanks for fielding the pull request.
I'm new to github so maybe it's just me being dense, but I'll have my colleague take a look at it tomorrow as well.
Best,Adam

**Comment by jackspirou** [comment]
@ammurphy i'm sure your new to github, but not dense.  :-)

I think the project could use better documentation to explain how to contribute and use the `clientjs/build.sh`.  Thanks for being the first contributor and pushing through this :)

**Comment by jackspirou** [comment]
@ammurphy I updated the file like we talked about. Here was the diff if you want to look at it: https://github.com/jackspirou/clientjs/commit/6cc081299150fa0a6ddefa8424c9144fe333f563

I simply took your code so thank you for contributing to this project :)

**Pull request closed without merging**
